config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
  resources :bookmarks, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy]  
  
  devise_for :users
   if Rails.env.development?
     mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :bookmarks
  has_many :reviews
  mount_uploader :image, BookImageUploader

  validates :title, presence: true
  validates :user_id, presence: true
  validates :author, presence: true
  validates :publisher, presence: true
  validates :price, presence: true, numericality: true
  validates :publish_date, presence: true
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many:books
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :rank, presence: true, inclusion: 1..5
  validates :body, presence: true, allow_blank: false
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # サムネイル画像にCarrierWaveで作成したUserThumbnailUploaderを使用
  mount_uploader :thumbnail, UserThumbnailUploader

  # バリデーションを設定
  validates :name, presence: true
  validates :agreement, presence: true, acceptance: {accept: true}  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # deviseのコントローラを実行する時は「configure_permitted_parameters」メソッドを実行する
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
     # 新規作成にname、thumbnail、agreementパラメータを含める
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :thumbnail, :agreement])
    end  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    bookmark = Bookmark.new
    bookmark.attributes = input_params
    bookmark.user_id = current_user.id
    if bookmark.valid? # バリデーションチェック
      bookmark.save!
      flash[:notice] = I18n.t('bookmark.created')
      redirect_to book_path(bookmark.book_id)
    else
      flash[:alert] = bookmark.errors.full_messages
      redirect_to request.referer
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    book_id = bookmark.book_id
    bookmark.destroy!
    flash[:notice] = I18n.t('bookmark.deleted')
    redirect_to book_path(book_id)
  end

  private
  def input_params
    params.require(:bookmark).permit(:book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @categories = Category.all
    if user_signed_in? && params[:ft] && params[:ft] == 'my'
      @books = Book.includes(:bookmarks, :reviews, :user).where(user_id: current_user.id).order('updated_at DESC')
    elsif user_signed_in? && params[:ft] && params[:ft] == 'bookmark'
      @books = Book.joins(:bookmarks).where('bookmarks.user_id = ?', current_user.id).order('updated_at DESC')
    elsif user_signed_in? && params[:category]
      @books = Book.includes(:bookmarks, :reviews, :user).where('books.category_id = ?', params[:category]).order('updated_at DESC')
    else
      @books = Book.includes(:bookmarks, :reviews, :user).order('updated_at DESC')
    end
  end
  
  def show
    @book = Book.find(params[:id])
     if user_signed_in?
       # 自分のブックマークの選択
       @my_bookmark = @book.bookmarks.select{|s| s.user_id == current_user.id}.first
     end
     if user_signed_in?
       # 自分のレビューの存在確認
       my_review = @book.reviews.select{|s| s.user_id == current_user.id}.first
       unless my_review
         # レビューが無い場合は入力フォームを作成
         @my_review = Review.new
       end
     end     
  end


  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.attributes = input_params
    @book.user_id = current_user.id
    if @book.valid? # バリデーションチェック
      @book.save!
      flash[:notice] = I18n.t('book.created')
      redirect_to action: :show, id: @book.id
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.attributes = input_params
    @book.user_id = current_user.id
    if @book.valid? # バリデーションチェック
      @book.save!
      flash[:notice] = I18n.t('book.updated')
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy!
    flash[:notice] = I18n.t('book.deleted')
    redirect_to action: :index
  end

  private
  def input_params
    params.require(:book).permit(:title, :author, :publisher, :price, :publish_date, :caption, :image, :category_id)
  end  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    review = Review.new
    review.attributes = input_params
    review.user_id = current_user.id
    if review.valid? # バリデーションチェック
      review.save!
      flash[:notice] = I18n.t('review.created')
      redirect_to book_path(review.book_id)
    else
      flash[:alert] = review.errors.full_messages
      redirect_to request.referer
    end
  end

  def destroy
    review = Review.find(params[:id])
    book_id = review.book_id
    review.destroy!
    flash[:notice] = I18n.t('review.deleted')
    redirect_to book_path(book_id)
  end

  private
  def input_params
    params.require(:review).permit(:book_id, :rank, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def review_average(reviews)
    reviews.length > 0 ? (reviews.inject(0) {|sum, r| sum + r.rank} / reviews.length.to_f).round(2) : 0
  end
end

app/views/books/_grid.html.erb
<%
  book = nil if book.nil?
%>

<li class="grid">

  <% if book %>
    <%= link_to book_path(book.id) do %>
      <div class="image">
        <% if book.image? %>
          <%= image_tag book.image.url %>
        <% else %>
          <div class="empty">No image</div>
        <% end %>
      </div>
    <% end %>
    <div class="title">
      <%= book.title %>
    </div>
    <div class="info">
      <!-- 下記を追加 -->
      <div class="bookmark">
        ♥ <%= book.bookmarks.length %>
      </div>
    </div>
    <div class="grid_footer">
      <%= render 'books/social_buttons', url: book_url(book.id) %>
    </div>
  <% end %>

</li>

app/views/books/_info.html.erb
<%
  book = nil if book.nil?
%>

<% if book %>
  ♥ <%= book.bookmarks.length %>   💬 <%= book.reviews.length %>   ★<%= review_average(book.reviews) %>
<% end %>

app/views/books/_input.html.erb
<div class="wrapper book_input">
  <div class="header">
    <%= link_to 'Bookリストに戻る', root_path %>
  </div>

  <hr>

  <h2>Book登録</h2>

  <%= form_for @book do |f| %>
    <!-- エラーメッセージ -->
    <% if @book.errors.any? %>
      <div class="alert alert-danger">
        <% @book.errors.full_messages.each do |message| %>
          <p class="alert"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br/>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author %><br/>
      <%= f.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :publisher %><br/>
      <%= f.text_field :publisher, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price %><br/>
      <%= f.number_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :publish_date %><br/>
      <%= f.date_field :publish_date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :caption %><br/>
      <%= f.text_area :caption, class: 'form-control', rows: 3 %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %><br/>
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {class: 'form-control'} %>
    </div>

    <div class="actions">
      <%= f.submit "登録", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/books/_review.html.erb
<div class="review clearfix">
  <div class="thumbnail">
    <% if review.user.thumbnail? %>
      <%= image_tag review.user.thumbnail.url %>
    <% else %>
      <div class="no_thumbnail"></div>
    <% end %>
  </div>
  <div class="review_contents">
    <div class="review_header clearfix">
      <%= review.user.name %>
      <div class="rank">
        <%= '★' * review.rank %><%= '☆' * (5 - review.rank) %>
      </div>
      <% if user_signed_in? && review.user.id == current_user.id %>
        <div class="delete">
          <%= button_to '削除', review_path(review.id), method: :delete, class: 'btn btn-danger', data: {confirm: '削除してよろしいですか？'} %>
        </div>
      <% end %>
    </div>
    <div class="review_body">
      <%= review.body %>
    </div>
  </div>
</div>

app/views/books/_social_buttons.html.erb
<div class="social_button clearfix">
  <div class="facebook">
    <div class="fb-share-button" data-href="<%= url %>" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%= ERB::Util.url_encode(url) %>&amp;src=sdkpreparse">シェア</a></div>
  </div>
  <div class="twitter">
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= url %>">Tweet</a>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'books/input' %>

app/views/books/index.html.erb
<div class="wrapper book_index">

  <hr class="bold">

  <div class="header">
    Bookリスト
  </div>
  <%= render 'books/social_buttons', url: request.url %>
  <hr>
    <!--下記追加-->
  <% if  user_signed_in? %>
    <div class="filter">
      <div <%= 'class=bold' unless params[:ft] %>><%= link_to '全て', root_path %></div>
      <div <%= 'class=bold' if params[:ft] && params[:ft] == 'my' %>><%= link_to '登録したBook', root_path(ft: 'my') %></div>
      <div <%= 'class=bold' if params[:ft] && params[:ft] == 'bookmark' %>><%= link_to 'ブックマーク', root_path(ft: 'bookmark') %></div>
    </div>
    <hr>

  <% end %>
  
  <div class="category">
    <% @categories.each do |category| %>
      <%= link_to category.name, root_path(category: category) %>
    <% end %>
  </div>
  <hr>
  
  <div>
  <%= button_to 'Bookを登録', new_book_path, method: :get, class: 'btn btn-primary' %>
  </div>

  <ul class="grid_wrapper clearfix">
    <% @books.each do |book| %>
      <%= render 'books/grid', book: book %>
    <% end %>
  </ul>

</div>

app/views/books/new.html.erb
<%= render 'books/input' %>

app/views/books/show.html.erb
<div class="wrapper book_show">
  <%= link_to 'Bookリストに戻る', root_path %>

  <hr>

  <div class="header">
    <%= @book.title %>
  </div>

  <div class="bookmark_and_social clearfix">
    <%= render 'books/social_buttons', url: request.url %>
    <!-- 下記を追加 -->
    <% if user_signed_in? %>
      <div class="bookmark">
        <% if @my_bookmark %>
          <!-- ブックマーク済 -->
          <%= button_to 'ブックマーク解除', bookmark_path(@my_bookmark.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <!-- 未ブックマーク -->
          <%= button_to 'ブックマーク', bookmarks_path(bookmark: {book_id: @book.id}), class: 'btn btn-primary' %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if user_signed_in? && @book.user_id == current_user.id %>
    <div class="edit clearfix">
      <div class="button_wrapper">
        <%= button_to '削除', book_path(@book.id), method: :delete, class: 'btn btn-danger', data: {confirm: '削除してよろしいですか？'} %>
      </div>
      <div class="button_wrapper">
        <%= button_to '編集', edit_book_path(@book.id), method: :get, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

  <div class="row">

    <div class="col-sm-4">
      <div class="image">
        <% if @book.image? %>
          <%= image_tag @book.image.url %>
        <% else %>
          <div class="empty">No image</div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-8">
      <div class="author">
        <%= label :book, :author %>: <%= @book.author %>
      </div>
      <div class="publisher">
        <%= label :book, :publisher %>: <%= @book.publisher %>
      </div>

      <div class="price">
        <%= label :book, :price %>: ¥<%= @book.price.to_s(:delimited) %>
      </div>

      <div class="publish_date">
        <%= label :book, :publish_date %>: <%= @book.publish_date.strftime('%Y年%m月%d日') %>
      </div>

      <div class="caption">
        <%= label :book, :caption %>: <%= @book.caption %>
      </div>
      <!-- 下記を追加 -->
      <div class="info">
      <!-- 変更 --> 
        <%= render 'books/info', book: @book %>
      </div>
    </div>
  </div>
      <!-- 新規追加 --> 
  <div class="my_review_wrapper">
    <% if @my_review %>
      <%= form_for @my_review do |f| %>
        <%= f.text_area :body, class: 'form-control', rows: 3, placeholder: 'レビューを書く' %>
        <div class="footer_menu clearfix">
          <div class="rank">
            <%= f.label :rank %> <%= f.select :rank, 5.downto(1).map { |m| [m, m] }, {}, class: 'form-control'%>
          </div>
          <div class="review_post">
            <%= f.submit 'レビュー', class: 'btn btn-primary' %>
          </div>
        </div>
        <%= f.hidden_field :book_id, value: @book.id %>
      <% end %>
    <% elsif user_signed_in? %>
      <b>レビュー済みです</b>
    <% end %>
  </div>

  <hr>

  <div class="review_wrapper">
    レビュー数 <%= @book.reviews.length %>件

    <div class="review_list">
      <% @book.reviews.each do |review| %>
        <%= render 'books/review', review: review %>
      <% end %>
    </div>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesBooklog</title>
   <%= stylesheet_link_tag 'application', media: 'all' %>
   <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
   <meta property="og:url"           content="<%= request.url %>" />
   <meta property="og:type"          content="website" />
   <meta property="og:title"         content="Bookリスト" />
   <meta property="og:description"   content="Bookリストのサイトです。" />
   <!--
   <meta property="og:image"         content="http://www.your-domain.com/path/image.jpg" />
   -->  
</head>
<body>
<!-- ログイン・ログアウト用のリンクを追加します -->
  <div class="login_logout_wrapper">
    <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "Log in", new_user_session_path %>
    <% end %>
  </div>
<!-- ここまで -->


<!-- 下記を追記 -->
<p class="notice"><%= notice %></p>

<%= yield %>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.7&appId=280989592245534";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</body>
</html>